### ISSUE TITLE
新的问题需要您的帮助

### ISSUE THREAD

**Issue by 234044174** [timmaia/esx_weaponshop#3]
您好，感谢提供帮助，我安装了该脚本并且成功登录了游戏，在武器店按“E”键出现了选购界面，但是退出选购界面后画面锁定了，不能动 且ESC  都不能解决只有 F8 quit 才能退出游戏！希望得到您的帮助！谢谢！

**Comment by carlosaaraujo** [comment]
Is this still happening?
